"""
Hybrid retrieval helpers: vector + full-text fusion with RRF.
"""
from dataclasses import dataclass
from types import SimpleNamespace
from typing import Any, Dict, Optional, Sequence


@dataclass
class RetrievalCandidate:
    chunk_id: int
    row: Any
    vector_score: Optional[float] = None
    text_score: Optional[float] = None
    vector_rank: Optional[int] = None
    text_rank: Optional[int] = None
    rrf_score: float = 0.0


def _get_row_id(row: Any) -> int:
    """Read row id from SQLAlchemy row-like object."""
    return int(getattr(row, "id"))


def _row_to_namespace(row: Any) -> Any:
    """
    Convert SQLAlchemy row-like objects to mutable namespace objects.
    """
    mapping = getattr(row, "_mapping", None)
    if mapping is not None:
        return SimpleNamespace(**dict(mapping))

    raw_dict = getattr(row, "__dict__", None)
    if isinstance(raw_dict, dict):
        return SimpleNamespace(**raw_dict)

    return row


def merge_rows_by_score(
    row_groups: Sequence[tuple[str, str, Sequence[Any]]],
    *,
    score_attr: str,
    query_attr: str,
    strategy_attr: str,
    limit: Optional[int] = None,
) -> list[Any]:
    """
    Merge multiple ranked row lists by row id, keeping the highest score row.

    Args:
        row_groups: Sequence[(strategy, query, rows)] where rows are ranked
            results generated by one query.
        score_attr: Attribute name containing comparable score.
        query_attr: Attribute name used to record matched query.
        strategy_attr: Attribute name used to record matched strategy.
        limit: Optional top-N limit after merge/sort.
    """
    best_rows: Dict[int, Any] = {}

    for strategy, query_text, rows in row_groups:
        for row in rows:
            row_obj = _row_to_namespace(row)
            row_id = _get_row_id(row_obj)
            score = float(getattr(row_obj, score_attr, 0.0) or 0.0)

            current = best_rows.get(row_id)
            current_score = (
                float(getattr(current, score_attr, 0.0) or 0.0)
                if current is not None
                else float("-inf")
            )
            if score > current_score:
                setattr(row_obj, query_attr, query_text)
                setattr(row_obj, strategy_attr, strategy)
                best_rows[row_id] = row_obj

    merged = sorted(
        best_rows.values(),
        key=lambda item: float(getattr(item, score_attr, 0.0) or 0.0),
        reverse=True,
    )
    if limit is not None and limit > 0:
        return merged[:limit]
    return merged


def fuse_rrf(
    vector_rows: Sequence[Any],
    text_rows: Sequence[Any],
    *,
    rrf_k: int = 60,
    limit: Optional[int] = None,
) -> list[RetrievalCandidate]:
    """
    Fuse vector ranking and text ranking with Reciprocal Rank Fusion.
    """
    if rrf_k <= 0:
        rrf_k = 60

    candidates: Dict[int, RetrievalCandidate] = {}

    for rank, row in enumerate(vector_rows, start=1):
        chunk_id = _get_row_id(row)
        candidate = candidates.get(chunk_id)
        if candidate is None:
            candidate = RetrievalCandidate(chunk_id=chunk_id, row=row)
            candidates[chunk_id] = candidate

        candidate.row = row
        candidate.vector_rank = rank
        candidate.vector_score = float(getattr(row, "similarity", 0.0))
        candidate.rrf_score += 1.0 / (rrf_k + rank)

    for rank, row in enumerate(text_rows, start=1):
        chunk_id = _get_row_id(row)
        candidate = candidates.get(chunk_id)
        if candidate is None:
            candidate = RetrievalCandidate(chunk_id=chunk_id, row=row)
            candidates[chunk_id] = candidate
        elif candidate.row is None:
            candidate.row = row

        candidate.text_rank = rank
        candidate.text_score = float(getattr(row, "text_score", 0.0))
        candidate.rrf_score += 1.0 / (rrf_k + rank)

    fused = sorted(
        candidates.values(),
        key=lambda item: (
            item.rrf_score,
            item.vector_score if item.vector_score is not None else -1.0,
            item.text_score if item.text_score is not None else -1.0,
        ),
        reverse=True,
    )

    if limit is not None and limit > 0:
        return fused[:limit]
    return fused
